improve gengotags
By passing a directory to gengotags, gengotags moves to this
directory before running gotags. Comes back afterwards

Simple gotags error checking

diff --git a/gengotags b/gengotags
--- a/gengotags
+++ b/gengotags
@@ -1,4 +1,9 @@
 #! /bin/bash
 # create a 'tags' file with gotags, including all files in and under
 # the current directory
-gotags -R=true . > tags
+pushd . > /dev/null
+DIR=${1:-$PWD}
+cd "${DIR}"
+gotags -R=true "${DIR}" > tags
+if [ $? -eq 0 ]; then echo go tags generated in \""${DIR}"\"; else echo "an error occured, tags NOT generated"; fi
+popd > /dev/null
