gostress: fix exit on test error

diff --git a/gostress b/gostress
--- a/gostress
+++ b/gostress
@@ -26,7 +26,13 @@ run() {
 
   while true ; do
     export GOMAXPROCS=$(( 1 + $(( RANDOM % 128 ))))
-    "./$PKG.test" "$@" 2>&1 || echo -ne "\ngostress stopped due to test failure" && exit 1
+
+    if "./$PKG.test" "$@" 2>&1; then
+      # run until test fails or script is signaled (ctrl-c for example)
+      continue
+    fi
+    echo -ne "\ngostress stopped due to test failure"
+    exit 1
   done
 }
 
